-- Restore c-k original functionality to enter digraphs
local getKeys = function()
  local keys = require("lazyvim.plugins.lsp.keymaps").get()
  keys[#keys + 1] = { "<c-k>", false, mode = "i" }

  return keys
end

return {
  "neovim/nvim-lspconfig",
  opts = {
    keys = getKeys(),
    servers = {
      lua_ls = {
        settings = {
          Lua = {
            diagnostics = {
              globals = { "vim", "LazyVim" },
            },
            runtime = {
              version = "LuaJIT",
              path = vim.split(package.path, ";"),
            },
            workspace = {
              library = {
                [vim.fn.expand("$VIMRUNTIME/lua")] = true,
                [vim.fn.expand("$VIMRUNTIME/lua/vim/lsp")] = true,
              },
            },
          },
        },
      },
      intelephense = {
        filetypes = { "php", "blade", "php_only" },
        files = {
          associations = { "*.php", "*.blade.php" },
          maxSize = 1000000,
        },
        environment = {
          includePaths = vim.fn.expand("~/.composer/vendor/php-stubs/"),
        },
        stubs = {
          "aerospike",
          "amqp",
          "apache",
          "apcu",
          "ast",
          "bcmath",
          "blackfire",
          "bz2",
          "calendar",
          "cassandra",
          "com_dotnet",
          "Core",
          "couchbase",
          "couchbase_v2",
          "crypto",
          "ctype",
          "cubrid",
          "curl",
          "date",
          "dba",
          "decimal",
          "dio",
          "dom",
          "ds",
          "eio",
          "elastic_apm",
          "enchant",
          "Ev",
          "event",
          "exif",
          "expect",
          "fann",
          "FFI",
          "ffmpeg",
          "fileinfo",
          "filter",
          "fpm",
          "frankenphp",
          "ftp",
          "gd",
          "gearman",
          "geoip",
          "geos",
          "gettext",
          "gmagick",
          "gmp",
          "gnupg",
          "grpc",
          "hash",
          "http",
          "ibm_db2",
          "iconv",
          "igbinary",
          "imagick",
          "imap",
          "inotify",
          "interbase",
          "intl",
          "json",
          "judy",
          "ldap",
          "leveldb",
          "libevent",
          "libsodium",
          "libvirt-php",
          "libxml",
          "lua",
          "LuaSandbox",
          "lzf",
          "mailparse",
          "mapscript",
          "mbstring",
          "mcrypt",
          "memcache",
          "memcached",
          "meminfo",
          "meta",
          "ming",
          "mongo",
          "mongodb",
          "mosquitto-php",
          "mqseries",
          "msgpack",
          "mssql",
          "mysql",
          "mysql_xdevapi",
          "mysqli",
          "ncurses",
          "newrelic",
          "oauth",
          "oci8",
          "odbc",
          "openssl",
          "opentelemetry",
          "pam",
          "parallel",
          "Parle",
          "pcntl",
          "pcov",
          "pcre",
          "pdflib",
          "PDO",
          "pdo_ibm",
          "pdo_mysql",
          "pdo_pgsql",
          "pdo_sqlite",
          "pgsql",
          "Phar",
          "phpdbg",
          "posix",
          "pq",
          "pspell",
          "pthreads",
          "radius",
          "random",
          "rar",
          "rdkafka",
          "readline",
          "recode",
          "redis",
          "Reflection",
          "regex",
          "relay",
          "rpminfo",
          "rrd",
          "SaxonC",
          "session",
          "shmop",
          "simple_kafka_client",
          "SimpleXML",
          "snappy",
          "snmp",
          "soap",
          "sockets",
          "sodium",
          "solr",
          "SPL",
          "SplType",
          "SQLite",
          "sqlite3",
          "sqlsrv",
          "ssh2",
          "standard",
          "stats",
          "stomp",
          "suhosin",
          "superglobals",
          "svm",
          "svn",
          "swoole",
          "sybase",
          "sync",
          "sysvmsg",
          "sysvsem",
          "sysvshm",
          "tidy",
          "tokenizer",
          "uopz",
          "uploadprogress",
          "uuid",
          "uv",
          "v8js",
          "wddx",
          "win32service",
          "winbinder",
          "wincache",
          "xcache",
          "xdebug",
          "xdiff",
          "xhprof",
          "xlswriter",
          "xml",
          "xmlreader",
          "xmlrpc",
          "xmlwriter",
          "xsl",
          "xxtea",
          "yaf",
          "yaml",
          "yar",
          "zend",
          "Zend OPcache",
          "ZendCache",
          "ZendDebugger",
          "ZendUtils",
          "zip",
          "zlib",
          "zmq",
          "zookeeper",
          "zstd",
          -- WordPress related
          "acf-pro",
          "acf-stubs",
          "genesis",
          "polylang",
          "woocommerce",
          "wordpress",
          "wordpress-global",
          "wordpress-globals",
          "wp-cli",
        },
      },
    },
  },
}
